name: gaussian_splatting_new
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - plyfile
  - tqdm
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1